workflows:
  version: 2
  "build webcomponeents":
    jobs:
      - build
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-yarn
          command: yarn install
      - run: yarn build
