version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run: yarn lint
workflows:
  test_my_app:
    jobs:
      - lint