orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: check_env          
          command: echo ${ NPM_TOKEN }

workflows:
  "build webcomponeents":
    jobs:
      - build
