workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-yarn
          command: yarn install
