version: '2.1'

orbs:
  node: circleci/node@4.7.0

default: &default
  executor: 
    name: node/default
    tag: '16.13.0'


jobs:
  lint:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run: yarn lint

  test:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run: yarn test

  build:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run: yarn build

  publish:
    <<: *default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run: 
          name: release-package 
          command: yarn release

workflows:
  test_my_app:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
      - publish:
          context: token_npm_github
          requires:
            - build