workflows:
  version: 2
  "build webcomponeents":
    jobs:
      - build
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-yarn          
          command: yarn install

      - run: 
          name: build_webcomponent 
          command: yarn build
