orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: install-yarn          
          command: yarn install

      - run: 
          name: build_webcomponent 
          command: yarn build
        
workflows:
  "build webcomponeents":
    jobs:
      - build
