version: 2.1

parameters:
  pkg_dir:
    type: string
    default: "./project/libs/webcomponent-xd-design"

orbs:
  node: circleci/node@4.7.0

default: &default
  executor: 
    name: node/default
    tag: '16.13.0'

aliases:
  - &description
    description: release the web package to github pages or static server

commands:
  install-packages:
    steps: 
      - checkout
      - run: node --version
      - run:
          name: Set NPM registry
          command: |
            echo ""
      - restore_cache:
          name: Restore Yarn package cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          name: Save Yarn package cache
          paths:
            - ~/project/node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - ./project

jobs:
  install:
    <<: *default
    steps:
      - install-packages

  lint:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint

  test:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test

  build:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - << pipeline.parameters.pkg_dir >>

  deploy:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: release-package-libs
          command: yarn deploy

workflows:
  test_my_app:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          context: token_npm_github
          requires:
            - lint
            - test
            - build