version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  lint:
    executor: 
      name: node/default
      tag: '16.13.0'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run: yarn lint

  test:
    executor: 
      name: node/default
      tag: '16.13.0'
      steps:
        - run: yarn test

workflows:
  test_my_app:
    jobs:
      - lint
      - test